version: "2"

volumes:
  db-data:
    external: false

services:
  db:
    image: mongo:3.6
    restart: always
    volumes:
      - ./db-data:/data/db

  memstore:
    image: redis:4-alpine
    restart: always

  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - memstore